apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: wordpress
  labels:
    name: wordpress
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io1
  iopsPerGB: "10"
  fsType: ext4
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-vc
  labels:
    name: wordpress-vc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: wordpress

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-vc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: wordpress
